### ISSUE TITLE
creates a different fingerprint on every monitor

### ISSUE THREAD

**Issue by DrOhReally** [Valve/fingerprintjs2#179]
I have 3 monitors and all 3 are generating a different fingerprint. Any way to get around this?

**Comment by Valve** [comment]
Read contributing.md

**Comment by DrOhReally** [comment]
this is a pretty fuckin major issue if a device is identified differently depending on which screen the browser is open, also please update your readme if you want people to use gitter.

**Comment by Valve** [comment]
if you have a "pretty fucking major" issue in an open-source project, you can stop using the project. You didn't pay me to develop it and I'm doing it just because I like programming, not because I need to solve your problems. 

If you really need a fix - please suggest a constructive idea or criticism. I doubt that your enraged expostulations will benefit this project in any way.

As for your issue: disable screen resolution fingerprinting, readme mentions wiki with all available options.

**Comment by DrOhReally** [comment]
You're the one who raged at me for opening a ticket, which contained my *issue* with a question attached to it. If you're getting hundreds of tickets with questions in them perhaps it's time to update the docs. thanks for the suggestion, I will try disabling some options. Way to be a dick and have a good day.

**Comment by Valve** [comment]
Your issue was a duplicate, you didn't take the time to read the contributing.md
Nobody does for some reason, don't know why, although the link about it is right above the issue text area. When people do it several times per week it's getting annoying.
I'd gladly help you solve all your issues if you ask in a proper place (such as gitter.im), because answering there is visible to many people and many people can see and answer your questions

**Comment by Valve** [comment]
Also, English is not my native lang, I don't know what this means "Way to be a dick"
Please explain
