### ISSUE TITLE
duplicate fingerprints from multiple user

### ISSUE THREAD

**Issue by kally007** [Valve/fingerprintjs2#183]
Hi i am getting same fingerprints for multiple users. Can u plz help me on this?

**Comment by Valve** [comment]
Hi @kally007 could you please let me know the details of these users? Are they on mobile devices? What are their user agents? Any technical info is helpful

**Comment by kally007** [comment]
when i am using this script i am getting duplicate fingerprints from multiple browsers.
Suppose my Chrom fingerprint hash is cc8b87eb4419e1d78c62ae80d58f95cc and i am getting the same from another user from chrome browser? So you have any solution for this?

**Comment by Valve** [comment]
What OS?

**Comment by kally007** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by Valve** [comment]
Yes, that's expected, this library never said there is a 100% accurate detection. Please read FAQ for more info.

**Comment by kally007** [comment]
I know this script has not 100% accurate detection but when i am using it for multiple mobile users it has accuracy of 20 or 30 % only.

So can we add anything into this script that make this script more accurate?

**Comment by Valve** [comment]
Why do you think it's 20% to 30%?
Did you test it on large enough data set with all possible phone models?
If so, please share with us your findings. I doubt it's 20-30%, just because there is not a single phone model which takes 30% of market. Even most popular iPhones models take 8-9% max from total market share (all apple devices are 15% from all world smartphones).
Different iPhone models will have different UserAgents hence different fingerprints.
