### ISSUE TITLE
Same fingerprint to 2 identical devices (android)

### ISSUE THREAD

**Issue by CaueArua** [Valve/fingerprintjs2#19]
I have 2 identical android devices (latest os and chrome version) , so I get the same fingerprint to both.

**Comment by Valve** [comment]
That's correct, this is how it should be, it's called device fingerprinting because of that. Once you begin using these devices separately (install new sofware/fonts/plugins etc), the fingerprints will diverge

**Comment by CaueArua** [comment]
The 2 devices have 6 month use by 2 different people, the only ting equal is OS and Chrome version.

**Comment by piront** [comment]
> "the only ting equal is OS and Chrome version."

Do you mean that the fingerprint is not well-generated or the fingerprints should be different because only these 2 variables should be equal on both devices ? (FYI https://github.com/Valve/fingerprintjs2#list-of-fingerprinting-sources)

Could you use a website like http://www.browserleaks.com/ to find which variable may be different or attach all the variables you get from the 2 devices (using fingerprintjs2) ?

For example my N5 only has 5 fonts detected through the js/css method (on browserleaks). Which is not a lot.

**Comment by CaueArua** [comment]
<blockquote>"The fingerprints should be different because only these 2 variables should be equal on both devices"</blockquote>

I mean even though the two devices have 6 month of usage and a complete different sort of apps having in common only  the model, the OS version and the Chrome version all of the variables used by fingerprintjs2  are identical. 

<blockquote> Could you ... attach all the variables you get from the 2 devices (using fingerprintjs2)?</blockquote>

<b> UserAgent</b> : Mozilla/5.0 (Linux; Android 5.0.2; XT1069 Build/LXB22.46-28) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36

<b>Language</b> : pt-BR

<b></b> : 
<b></b> :
<b></b> :



[colorDepthKey : 32];
[screenResolutionKey : undefined];
[timezoneOffsetKey : 180];
[sessionStorageKey : sessionStorageKey];
[localStorageKey : localStorageKey];
[indexedDbKey : indexedDbKey];
[addBehaviorKey : undefined];
[openDatabaseKey : openDatabase];
[cpuClassKey : navigatorCpuClass: unknown];
[platformKey : navigatorPlatform: Linux armv7l];
[doNotTrackKey : doNotTrack: unknown];
[pluginsKey : ];

**Comment by Valve** [comment]
@CaueArua I wonder why the plugins info is empty. I'll test the android + Chrome today or tomorrow.
What's the phone name, os version + chrome version?

**Comment by Valve** [comment]
@CaueArua I've just pushed some improvements to the canvas fp, please test it if you can (latest master). I'm still testing the android + chrome issue

**Comment by Valve** [comment]
@CaueArua I've connected to the android device and found 2 issues:
1. No plugins are enumerated at all. PluginArray is empty.
2. No flash is loaded, so the entire font list is not detected.

I'm looking into both, these are definitely bugs.

**Comment by Valve** [comment]
@CaueArua  Ok, another update. Plugins are not enumerated, because there are no plugins in Chrome on Android.
Flash is not loaded, because it's not supported there at all. Obviously, I wasn't fully aware of the plugins & Flash support on Chrome + Android. 
So, from FP2 view point, your 2 devices are identical. We need to keep improving FP2 in order to find more FP sources to be able to differentiate identical android devices.

So, from the fingerprintjs2 perspective, your

**Comment by cxytomo** [comment]
@Valve got the same bug on my iphone safari. got empty plugins
