### ISSUE TITLE
bug: wechat in iphone 6s plus 

### ISSUE THREAD

**Issue by diamont1001** [Valve/fingerprintjs2#209]
Test Link: http://valve.github.io/fingerprintjs2/

Apps: [wechat](https://itunes.apple.com/cn/app/wei/id414478124) 6.3.31

Platform: iphone 6s plus

System: 10.1.1（14B100)

It get the same fingerprint as below in two mobile equipments.

9e1bafae16631fd24f48e70939cb1b00

**Comment by Valve** [comment]
I would appreciate a PR for this. I don't have Iphone6 and Wechat so cannot fix it myself

**Comment by jonashaag** [comment]
Are you getting these on two identical iPhones (same model, same OS version, etc.)?

iPhones and other common smartphones are very difficult to distinguish from each other because most or all of the components are identical. It's actually impossible to distinguish iPhones that have the same model, OS version, browser, etc.

**Comment by diamont1001** [comment]
@jonashaag yes. i see, thank you 👍

**Comment by jonashaag** [comment]
We should add a comment about this somewhere.
