### ISSUE TITLE
Way to have fingerprint generation be synchronous?

### ISSUE THREAD

**Issue by minglethepringle** [Valve/fingerprintjs2#269]
I'm trying to use fingerprintjs2 like this:

    function generateFingerprint(){
            new Fingerprint2({
                excludeAdBlock: true
            }).get(function(result){
                alert(result);
                return result;
            });
    }

    function init(){
        var f = generateFingerprint();
        alert(f);
    }
    init();

When I do this, f is undefined every single time even though the alert for the result is the correct fingerprint. This leads me to believe that when I call `new Fingerprint2()`, it starts an asynchronous thread  to generate the fingerprint.

I want it to generate synchronously, so I can actually get a value for `f`. Is there a way to do this?

**Comment by jonashaag** [comment]
No, why would you want this?

**Comment by rporrass** [comment]
My case of use.

I want to add the fingerprint to every request for security checks.

It's kind of annoying having to provide a call to get the fingerprint a define the callback with the request inside. looks more natural a simple get for the hash and add it as a header in the request.

Already tried to have it initialized as a constant, but in some cases the request is done before the constant is initialized.

**Comment by minglethepringle** [comment]
I forgot about this thread, oops

I suggest that there be an optional option, maybe called `synchronous`, and if it's true then simply run it synchronously.

Like this:

```
 new Fingerprint2({
            excludeAdBlock: true,
            synchronous: true
        }).get(function(result){
            alert(result);
            return result;
        });
```

**Comment by jonashaag** [comment]
The "fonts" component works asynchronously internally, so if you want a synchronous solution you're not going to be able use that. We could add an option for synchronous fingerprint without fonts, if that's what you're interested in.

**Comment by minglethepringle** [comment]
That could work, sure.

**Comment by jonashaag** [comment]
I don't see much value in it, sorry. You should simply use asynchronous processing like you do all the time when using Javascript.

If someone wants to add the option, PR welcome.

**Comment by SmirMax** [comment]
**jonashaag**, can you please give an example of synchronous obtaining a fingerprint?

**Comment by Valve** [comment]
@SmirMax currently the library *is* synchronous, it just has a "done" callback, which gets called synchronously. The only way to to make it asynchronous is to pass `excludeJsFonts` option, which will try to use Flash to detect fonts and that operation *is asynchronous*.

**Comment by uiii** [comment]
@Valve As I looked in the code, the library **is not** synchronous, because the `jsFontsKey` function wraps its body in `setTimeout` which makes it asynchronous. Yes, the timeout is just 1ms but is still doesn't make it synchronous, meaning that the code after `new Fingerprint2().get(done)` will be called before the `done` callback.

**Comment by jonashaag** [comment]
@uiii He's confused the words asynchronous and synchronous obviously

**Comment by minglethepringle** [comment]
@jonashaag that certainly helps /s

**Comment by Valve** [comment]
@uiii @jonashaag  I didn't confuse the words, I wasn't clear, sorry for the confusion.
Let me explain how it was:

Originally (like in 2013), the library was asynchronous, because it called Flash object for font detection. Asynchronously calling flash object was the only option back then. 

After some time flash became less and less popular and not running at all on most mobile browsers. So I decided to disable flash font detection and instead write a JS-based font detection. The first version of JS-based font detection was synchronous (I am not confusing it here, you didn't need callbacks to run it).

After some time users started complaining that running fjps2 blocks main thread on slow devices because of heavy dom manipulation/css styling that was needed for js-based font detection.  I needed a way to avoid this. Originally I wanted to move all js-based font detection into a web worker, but web workers cannot touch DOM and can only work with serialized/passed data. So the only option to make js-based font detection was to create a pseudo-async call via setTimeout, which I did in this commit: https://github.com/Valve/fingerprintjs2/commit/320ddf909c9c2754fb1942f1ed6161f0f6c1c764

So technically, the library is asynchronous now (in a sense that you need a callback), but it was synchronous and can be easily made one again. 

Sorry again for the confusion.

**Comment by uiii** [comment]
Thank @Valve for clarification. So there is a way to make the `done` callback synchronous by using these options 
```
{
    excludeJsFonts: true,
    excludeFlashFonts: true
}
```

Maybe there will be better to abandon Flash font detection and make the library purely synchronous, using return instead of callback and leave up to the user to generate the fingerprint using `setTimeout` for pseudo async if neccessary.

**Comment by uiii** [comment]
BTW what is `fjps2`? Did you mean `fpjs2` as abbreviation of FingerprintJS2?

**Comment by Valve** [comment]
@uiii  yes, maybe, but most users use defaults, so it made sense at that time to add setTimeout. Yes, if you disable font detection entirely the lib will become synchronous. But w/out font detection it will be almost useless. fpjs2, sorry, not fjps2 :) yes

**Comment by dczaretsky** [comment]
I second the need for a syncronuous implementation that includes the jsfonts. We would like to integrate this function into a broader program, and having a synchronous wait simplifies things by ensuring all dependencies are completed prior to execution.

Having a choice of sync vs async is pretty standard.

That said, I’m wondering if anyone has bothered to run timing analysis on the code across different browsers and platforms to get a sense of execution time. I haven’t see any posts on this and wondering if this can be used in real time applications.

**Comment by jonashaag** [comment]
And akk of your other dependencies are synchronous? How come, in JS land?

Happy to accept a patch that makes things synchronous.

Timings are in the README, Firefox and Chrome and Safari are similar and IE is 3x-10x slower

**Comment by joeyzone** [comment]
> Thanks @Valve for clarification. So there is a way to make the `done` callback synchronous by using these options
> 
> ```
> {
>     excludeJsFonts: true,
>     excludeFlashFonts: true
> }
> ```
> Maybe there will be better to abandon Flash font detection and make the library purely synchronous, using return instead of callback and leave up to the user to generate the fingerprint using `setTimeout` for pseudo async if neccessary.

also excludeAudioFP

**Comment by Valve** [comment]
closing because calling the lib synchronously was never an intended feature

**Comment by supershowwei** [comment]
I added a simple `getSync()` in released `fp.js` file. It removed asynchronous factors of fingerprint generating for trade-off. This is just contingency plan, hope it helps.

https://github.com/supershowwei/synchronous-fingerprintjs

**Comment by csalmeida** [comment]
Thanks @supershowwei, great library and your additions [allow for some more flexibility](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) when dealing with certain scenarios like avoiding additional React `useEffect`s for example.
