### ISSUE TITLE
Suggestion - Add a way to estimate if two users share a lot of similarities

### ISSUE THREAD

**Issue by BarbzYHOOL** [Valve/fingerprintjs2#306]
If I want to identify unique users, the string given by fingerprintjs2 will greatly differ even if only one small attribute changed (for example if the user updated his firefox from v 70.0 to 70.2). Am I right with that ?

If so, would there be a way to have a pretty similar string or result from fingerprintjs2 to make comparisons based on that?

**Comment by jonashaag** [comment]
Yes, since it uses a cryptographic hash function. But the second value you're getting is the details of all of the components that were used for fingerprinting. You can compare these values to compute a similarity scoring yourself.

**Comment by BarbzYHOOL** [comment]
Yes, I suppose... :'(

**Comment by Valve** [comment]
this will probably not be implemented.

**Comment by NitroBAY** [comment]
I was thinking about how preventing my users sharing theirs accounts whose price is in the hundreds of dollars to other students. And I suddenly realized that storing the fingerprint in the browser (localStorage) and returning it as long as the user does not clean the data of his browser may be a partial solution.
Obviously if a user cleans his data + update his browser (for example) he will consider using a new device.
It's really hard to find a good way to block sharing accounts.
Probably one could try a mix of those : blocking too many different IP address or fingerprint, forcing to use a third party like Google account which forces the user to double authenticate sometimes or Facebook because no one shares Facebook credentials, storing an ID to the storage of the device to authenticate it, a maximum number of different devices (fingerprint) which can connect to one account, double authentication with email.
