### ISSUE TITLE
Problem when try to get two fingerprint in chrome

### ISSUE THREAD

**Issue by gazhikaba** [Valve/fingerprintjs2#34]
I try to get two fingerprint with different options, but only "fp2" has value in chrome(IE 9 is same).
And It's run well in Firefox.
I debug the code, following code at line:688 is not run in first time calling.
```javascript
      window[hiddenCallback] = function(fonts) {
        done(fonts);
      };
```
### Html 
```html
<script src="js/fingerprint2.js" ></script>
<script src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject_src.js"></script>
... ...
<td id='fp1'></td><td>excludeUserAgent, excludeDoNotTrack</td>
... ...
<td id='fp2'></td><td>excludeUserAgent, excludeDoNotTrack, excludeWebGL</td>
... ...
<script type="text/javascript">
var options = { excludeUserAgent: true, excludeDoNotTrack:true};
var fp = new Fingerprint2(options);
  fp.get(function(result) {
    console.log("result:"+result);//zzz
      document.getElementById('fp1').innerHTML = result;
  });
  
	options = { excludeUserAgent: true, excludeDoNotTrack:true, excludeWebGL:true};
	fp = new Fingerprint2(options);
  fp.get(function(result) {
      console.log("result:"+result);//zzz
        document.getElementById('fp2').innerHTML = result;
  });
  
</script>
```

**Comment by Valve** [comment]
@gazhikaba with the new version, this issue should be solved, because currently FP2 does not use the SWF font detection by default. 
If you decide to enable the SWF font detection (not recommended, because the results will be different in normal vs incognito mode), there is this limitation to only use one instance of FP on the page. This is because there is a hardcoded callback identifier for SWF code.
