### ISSUE TITLE
Getting different fingerprints for the same browser

### ISSUE THREAD

**Issue by savinay** [Valve/fingerprintjs2#38]
I am getting different fingerprints after say 2-3 hours for the same browser. Can anybody let me know what the issue is?

**Comment by Valve** [comment]
@savinay, please provide more info, which browser/version, OS. Very helpful would be the key values the FP2 is collecting to see what's changing.

**Comment by timkolesa** [comment]
With Pale Moon you don't have to wait 2-3 hours. 
Just open a new tab and load again and you get different results.
Seems to work well with all common browsers. That's why I like Pale Moon.
Browser: Pale Moon ver. 25.5.0
OS: Win 7

**Comment by timkolesa** [comment]
This version of fingerprint2.js at this site (http://www.urlconcepts.com/) does work with Pale Moon.

**Comment by Valve** [comment]
@timkolesa this web site is using an old version of FP2. Please update it first to the latest.

**Comment by timkolesa** [comment]
Yes, that was what I was pointing out. The newest version of fingerprint2.js which I downloaded yesterday returns different results each time it is run in the Pale Moon browser. The older version that I downloaded from the referenced site works correctly. I thought that might help pin down where in the newest version Pale Moon is failing.

**Comment by Valve** [comment]
@timkolesa , OK, I'll look into it. Although I've never heard about Pale Moon thing.

**Comment by Valve** [comment]
@timkolesa, confirming the issue in PaleMoon. Will fix soon.

**Comment by Valve** [comment]
@timkolesa, figure it out. Pale Moon randomizes the order of returned plugins. So every time you refresh the page, the list of plugins is different. One way to fix this is to sort the list, which will decrease the entropy.

**Comment by Valve** [comment]
I've opened an issue to fix this: https://github.com/Valve/fingerprintjs2/issues/56

**Comment by timkolesa** [comment]
On 7/13/2015 11:01 AM, Valentin Vasilyev wrote:
>
> @timkolesa <https://github.com/timkolesa>, figure it out. Pale Moon 
> randomizes the order of returned plugins. So every time you refresh 
> the page, the list of plugins is different. One way to fix this is to 
> sort the list, which will decrease the entropy.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Valve/fingerprintjs2/issues/38#issuecomment-120979647>.
>
You should only do this for the Pale Moon browser and not all others 
because the order routinely produced by other browser may be 
significant. May be test plugins twice. If lists differ, then sort. Just 
a thought.

see http://forum.palemoon.org/viewtopic.php?f=3&t=4406

Tim

**Comment by Valve** [comment]
@timkolesa, it's not possible to get the list of plugins twice, because they maintain the order when reading the property. The order is randomized on page refresh only.

Please see my ticket update: https://github.com/Valve/fingerprintjs2/issues/56#issuecomment-121140530

So to partially address it,

**Comment by mhuisman** [comment]
Looks like Pale Moon was (crudely) attempting to defeat fingerprinting.
