### ISSUE TITLE
has lied OS & has lied resolution accuracy 

### ISSUE THREAD

**Issue by fehza123** [Valve/fingerprintjs2#396]
We have been recording fingerprints using fingerprintjs2 for nearly 10 months now across tons of unique users a month. In that time, we've realized that fingerprints can overlap and that has lied OS/has lied resolution may not be very accurate. We see this on some users, dig deep, and simply don't see any other signs of faking OS or resolution. In some cases, we ban those users only to have them reach out and verify they are in fact real. 

I know there is one bug where touch screen laptops are considered lying about the OS, and we're fixing that. But, is there any other considerations with either? We're trying to get this data to a point that it's more actionable/less false positives. 

Thanks!

**Comment by jonashaag** [comment]
Maybe it's a logic bug. If you could share a list of `window.screen.{width,availWidth || height,availHeight}` and `navigator.userAgent`, `navigator.oscpu`, `navigator.platform`, `navigator.maxTouchPoints`, `navigator.msMaxTouchPoints`, `navigator.plugins`, we can try to debug it further

**Comment by mads1980** [comment]
Related to https://github.com/Valve/fingerprintjs2/issues/493 and https://github.com/Valve/fingerprintjs2/issues/247

**Comment by mads1980** [comment]
We have also found hasLiedOs to be unreliable in these cases:

- User-Agents containing "Windows Phone" (probably because MS Edge pretends to be Safari, Chrome, Gecko, etc. everything at the same time: http://www.davevoyles.com/2015/01/28/microsofts-spartan-browser-uses-chrome-ua-string/

- Opera and Opera Mini

- User-Agents containing "CriOS" (Chrome for iOS) and "FxiOS" (Firefox for iOS)
