### ISSUE TITLE
Uncaught TypeError: fingerprintjs2__WEBPACK_IMPORTED_MODULE_6__.get is not a function

### ISSUE THREAD

**Issue by fengerwoo** [Valve/fingerprintjs2#409]
yarn add fingerprintjs2

<pre>
<code>
import * as Fingerprint2 from 'fingerprintjs2'

Fingerprint2.get({
        preprocessor: function(key, value) {
            return value
        }
    },function(components){
        let values = components.map(function (component) { return component.value });
        let device_id = Fingerprint2.x64hash128(values.join(''), 31);
        console.log("device_id",device_id)
    });
</code>
</pre>

Uncaught TypeError: fingerprintjs2__WEBPACK_IMPORTED_MODULE_6__.get is not a function

**Comment by masteronelight** [comment]
I also encountered this problem and later solved it. 
The reason is that the default installation is version 1.8. The 1.8 version does not support this method. See which version is in your package.json file. You need to install the latest version 2.0. 
**Use the command: npm install fingerprintjs2@2 --save**
Good luck~!

**Comment by masteronelight** [comment]
> yarn add fingerprintjs2
> 
> ```
> 
> import * as Fingerprint2 from 'fingerprintjs2'
> 
> Fingerprint2.get({
>         preprocessor: function(key, value) {
>             return value
>         }
>     },function(components){
>         let values = components.map(function (component) { return component.value });
>         let device_id = Fingerprint2.x64hash128(values.join(''), 31);
>         console.log("device_id",device_id)
>     });
> ```
> Uncaught TypeError: fingerprintjs2__WEBPACK_IMPORTED_MODULE_6__.get is not a function

I also encountered this problem and later solved it.
The reason is that the default installation is version 1.8. The 1.8 version does not support this method. See which version is in your package.json file. You need to install the latest version 2.0.
Use the command: npm install fingerprintjs2@2 --save
Good luck~!

**Comment by Valve** [comment]
closing, please reopen if necessary
