### ISSUE TITLE
why not using md5 replace murmur hash ?

### ISSUE THREAD

**Issue by zhenchuan** [Valve/fingerprintjs2#422]
Murmur hash has a chance of collision, but md5 is unique. 
Isn't it better to use md5 to generate fingerprints?

**Comment by adam-rocska** [comment]
@zhenchuan ,: Just to be an ass here, mathematically speaking md5 can also have collisions. However, the chances of collision are way lower than of murmur.

**Comment by Valve** [comment]
For an overview of modern non-crypto hashes, see this excellent SO answer: https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed

I chose MurmurHash because I liked the name :) You can replace it with any hash algorithm that works for you, but at that time I felt that Murmurhash was easy to implement in Javascript, had nice performance and hashing characteristics
