### ISSUE TITLE
How to use synchronously

### ISSUE THREAD

**Issue by nebi-frame** [Valve/fingerprintjs2#448]
Hi , https://github.com/Valve/fingerprintjs2/issues/269 I followed this issue to use fingerprintjs2 synchronously. This is what I came up so far
```
  const options = { excludes: { fonts: true, fontsFlash: true, audio: true }, this: this };
  Fingerprint2.getPromise(options).then((components) => {
    const my_obj = {};
    components.map((component) => {
      my_obj[component.key] = component.value;
    });
    const merged_final = { ...this.result, ...my_obj };
    this.result = merged_final;
  });
```
But it seems it's still async, anyways to make this sync ?

**Comment by Valve** [comment]
the lib uses several calls to `setTimeout`, e.g. : https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L371
https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L1297
So you'll need to avoid using them.

Overall I think that currently there is no good way to call it synchronously while keeping all sources. 
I'm closing this because synchronous call was never a feature.
