### ISSUE TITLE
Learn to avoid being blocked by FP blocking tools

### ISSUE THREAD

**Issue by Valve** [Valve/fingerprintjs2#65]
There are tools out there, that replace Canvas#toDataURL and thus make FPing useless.
Example of these tools: https://chrome.google.com/webstore/detail/canvasfingerprintblock/ipmjngkmngdcdpmgmiebdmfbkcecdndc/related

We need to learn how to avoid being blocked by them. For example, create a canvas in an iframe might help.
```html
<iframe id="iframe" sandbox="allow-same-origin" style="display:none"></iframe>;
<script>
var canvas = document.getElementById("iframe").contentDocument.createElement('canvas');
...
</script>
```

**Comment by igor-im** [comment]
Careful they know about you :)
https://lh3.googleusercontent.com/MREuDLuqjHuM9IaczZsg_Ih-CFAYt-2V9aQ5E9XupwapV6ThJnKh7lQUImOcu0Dm_G4WCQCH1Q=s1280-h800-e365-rw

**Comment by igor-im** [comment]
Line 640:       if (gl.canvas != null) { try { result.push(gl.canvas.toDataURL()); } catch(e) { console.log('doh'); } }

Not really a solution, but it doesn't bomb the whole FP process

**Comment by Valve** [comment]
I don't understand your last 2 comments.

**Comment by igor-im** [comment]
Sorry too late at night on the last one :)
If you attempt fingerprinting with that Chrome extension turned on on, the Fingerprint crashes when it attempts to evaluate 

    Line 640: if (gl.canvas != null) { result.push(gl.canvas.toDataURL()); }

it's crashing because the extension is overriding the HTMLCanvasElement.prototype.toDataUrl, which is weird, because the toDataUrl in the Canvas (not Webgl) fingerprint works well.
This is preventing the fingerprint from continuing, and thus never generates the hash
Wrapping the result.push in a try catch allows the fingerprint to continue, and generates the hash

**Comment by Valve** [comment]
some more links: 
https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode
https://github.com/dillbyrne/random-agent-spoofer

**Comment by Valve** [comment]
I'm sorry for closing, but we'll be concentrating on stabilizing the library, not on adding new features in the foreseeable future. Closing as a non-feature.
