### ISSUE TITLE
Update readme: how to get a per-device fingerprint

### ISSUE THREAD

**Issue by lorensr** [Valve/fingerprintjs2#80]
I'd like a fingerprint to stay the same until the user changes devices. I take it that since for example the UA is used, when the browser version is updated, the fingerprint changes? It looks like I can use the `excludeUserAgent` option, but are there other options I need to use to make sure the fingerprint stays the same? Thanks!

**Comment by mhuisman** [comment]
I would like to have the default behavior of fpjs2 be detection of immutable fingerprint data, with options to enable mutable fingerprint data if the end user so chooses

**Comment by Valve** [comment]
well, this is a tricky task. This lib is a browser fingerprinting, not a device or user identification. 
Disabling userAgent will not help, because there is a lot of browser-specific FP sources, such as canvas/webgl/html5 etc. Disabling all of them will make the library useless. I've already written on the gitter channel that if one wants to be able to track devices or users, his best bet would be to use a commercial product, such as Augur.io.  Otherwise you'd need to roll the entire solution yourself. This requires cookie syncing, persistent cookie storage etc. This is not possible without a server-side component in my opinion.

**Comment by lorensr** [comment]
Thanks! If I assume that the user is using the same browser (in my case, an in-app mobile browser), is there a way to just prevent fingerprint from changing when the browser updates?

**Comment by Valve** [comment]
@lorensr, to be able to survive browser upgrades - we can use 2 things: (ideally both, but either one is good too)
1. we need a UA parser (very minimal one, but functional). This way we can grab the UA info minus the versions. 

2. fuzzy hashing (locale sensitive) to assign very low weight to the UA component. 

So ideally we need both to maintain the same FP even when the browser changes over time.

Of course, you can just exclude the UA, but this is very crude and somewhat defeats the purpose of the lib, because UA is an important component.

**Comment by lorensr** [comment]
Got it – this looks good:

https://github.com/faisalman/ua-parser-js

Is there a way I can provide custom data to the fingerprinter, or do I need to do a PR?

**Comment by Valve** [comment]
No, unfortunately, no custom data support. If you want it, please do a PR

**Comment by mhuisman** [comment]
@Valve I wasn't trying to modify the core mission of the library, more just stating what my main interest is -- device fingerprint vs. browser fingerprint

**Comment by Valve** [comment]
Yeah, sure, np, @mhuisman
